exp:
    base_dir: '/home/kyle/Desktop/r2d2'  # Absolute path to your r2d2 repo
    exp_name: 'debug'
    log_dir: '{base_dir}/logs/{exp_name}_{date_time}'
    device: 'cuda'
    trained_on_multi_gpus: false

robot:
    robot_name: 'Panda'
    n_kp: 7

r2d2:
    data_folder: '/home/kyle/Desktop/data/r2d2_household/pen_in_several/Fri_Apr_21_10_42_22_2023'
    annotated_subfolders: [
        Fri_Apr_21_10_42_22_2023,
    ]
    scale: 1.0
    height: 720                 # H, W after scaling
    normalize: false
    width: 1280
    mean: [0.485, 0.456, 0.406] # Per-channel mean and std
    std: [0.229, 0.224, 0.225]
    camera_ids: ['23404442_left', '23404442_right', '29838012_left','29838012_right']
    camera_id: '23404442_right'
    batch_size: 1
    num_workers: 1
    shuffle: false

ctrnet:
    pretrained_keypoint_seg_model_path: '{base_dir}/ctrnet/weights/panda/panda-3cam_azure/net.pth'
    urdf_file: '{base_dir}/ctrnet/urdfs/Panda/panda.urdf'
    training_params:
        lr: 1e-6
        beta1: 0.9
        n_epoch: 500
        out_dir: 'results/debug'
        ckp_per_epoch: 10
        reproj_err_scale: 0.01

sam:
    checkpoint: '/home/kyle/Desktop/models/sam_segment_anything/sam_vit_h_4b8939.pth'
    model_type: 'vit_h'
    inference_params:
        batch_size: 2