r2d2:
    camera_id: '23404442_right'
    batch_size: 8
    num_workers: 8
    shuffle: True

ctrnet:
    training_params:
        lr: 1e-6
        beta1: 0.9
        n_epoch: 500
        out_dir: 'results/debug'
        ckp_per_epoch: 10
        reproj_err_scale: 0.01